### PR TITLE
Refactor work

### PR DESCRIPTION
**Pull request by GetTuh**
I've refactored the code, done some of the todos in the code as well as some small ironing out the syntax.

### CODE REVIEW

**Comment by GetTuh** [comment]
Pull request isn't ready: requires transpiled code check

**Comment by GetTuh** [comment]
Bug fixed, now everything is working. 

Tested with internal marketplace, run can be found here:
https://gh.asml.com/asml-gh/actions-marketplace-testing/runs/458856?check_suite_focus=true
And the output data of them: 
https://gh.asml.com/asml-gh/actions-marketplace-testing/blob/gh-pages/actions-data.json
https://gh.asml.com/asml-gh/actions-marketplace-testing/blob/gh-pages/internal-actions-data.json

Found [47] actions in [646] repos, exactly the same as before the rewrite here: 
https://gh.asml.com/asml-gh/actions-marketplace/runs/455486?check_suite_focus=true

**Review by rajbos — APPROVED** [review]
Looks good, thanks! I'll release a new patch version for this.

**Review by rajbos — CHANGES_REQUESTED** [review]
Tests are failing, looks like they need to be updated as well 😄 .

**Review by rajbos — APPROVED** [review]

**Comment by rajbos** [comment]
@GetTuh , please rebase your fork to fix the conflicts 😄

**Review by rajbos — APPROVED** [review]
LGTM

**Pull request merged**
